import { createClient } from '@/utils/supabase/server';
import { redirect } from 'next/navigation';
import { UploadCloud } from 'lucide-react';

export default async function SubmitGamePage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    redirect('/login');
  }

  // Ensure they have a profile
  const { data: profile } = await supabase
    .from('developers')
    .select('id')
    .eq('id', user.id)
    .single();

  if (!profile) {
    redirect('/developer/onboarding');
  }

  const submitGame = async (formData: FormData) => {
    'use server';
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    const title = formData.get('title') as string;
    const description = formData.get('description') as string;
    const iframe_url = formData.get('iframe_url') as string;
    const thumbnail_url = formData.get('thumbnail_url') as string;
    const category = formData.get('category') as string;
    
    // Convert comma separated string to array
    const tagsStr = formData.get('tags') as string;
    const tags = tagsStr ? tagsStr.split(',').map(t => t.trim()).filter(Boolean) : [];

    // The database trigger will override this, but we explicitly pass pending anyway.
    // slug is auto-generated by DB, status defaults to 'pending'
    const { error } = await supabase.from('games').insert({
      developer_id: user.id,
      title,
      description,
      iframe_url,
      thumbnail_url: thumbnail_url || null,
      category,
      tags
    });

    if (error) {
      console.error(error);
      return redirect('/developer/submit?error=submission_failed');
    }

    redirect('/developer?success=game_submitted');
  };

  return (
    <div className="max-w-3xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Submit New Game</h1>
        <p className="text-neutral-400">
          Your game must be hosted securely via HTTPS and will be reviewed before appearing on Aqua Spin.
        </p>
      </div>

      <div className="bg-neutral-900/50 border border-neutral-800 rounded-2xl p-8 backdrop-blur-md">
        <form action={submitGame} className="flex flex-col gap-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-neutral-300 mb-1">Game Title <span className="text-red-500">*</span></label>
              <input
                name="title"
                required
                maxLength={100}
                placeholder="Awesome Game 3D"
                className="w-full bg-neutral-950 border border-neutral-800 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-cyan-500 transition-colors"
              />
            </div>

            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-neutral-300 mb-1">Iframe URL (Must be HTTPS) <span className="text-red-500">*</span></label>
              <input
                name="iframe_url"
                type="url"
                required
                pattern="https://.*"
                title="URL must start with https://"
                placeholder="https://your-domain.com/game"
                className="w-full bg-neutral-950 border border-neutral-800 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-cyan-500 transition-colors"
              />
              <p className="text-xs text-neutral-500 mt-1">
                The secure link where your game is hosted. We will embed this in our sandbox.
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-1">Category <span className="text-red-500">*</span></label>
              <select 
                name="category"
                required
                className="w-full bg-neutral-950 border border-neutral-800 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 transition-colors"
              >
                <option value="Action">Action</option>
                <option value="Puzzle">Puzzle</option>
                <option value="Strategy">Strategy</option>
                <option value="RPG">RPG</option>
                <option value="Arcade">Arcade</option>
                <option value="Sports">Sports</option>
                <option value="Casual">Casual</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-1">Thumbnail URL</label>
              <input
                name="thumbnail_url"
                type="url"
                pattern="https://.*"
                placeholder="https://your-domain.com/thumb.jpg"
                className="w-full bg-neutral-950 border border-neutral-800 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-cyan-500 transition-colors"
              />
            </div>

            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-neutral-300 mb-1">Description</label>
              <textarea
                name="description"
                rows={4}
                className="w-full bg-neutral-950 border border-neutral-800 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-cyan-500 transition-colors"
                placeholder="Tell players about your game..."
              ></textarea>
            </div>

            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-neutral-300 mb-1">Tags</label>
              <input
                name="tags"
                placeholder="multiplayer, pixel-art, platformer (comma separated)"
                className="w-full bg-neutral-950 border border-neutral-800 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-cyan-500 transition-colors"
              />
            </div>
          </div>

          <div className="border-t border-neutral-800 pt-6 flex justify-end">
            <button className="bg-cyan-500 hover:bg-cyan-400 text-black font-semibold rounded-lg px-6 py-3 transition-colors flex items-center gap-2">
              <UploadCloud className="w-5 h-5" /> Submit for Review
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
